(() => {
'use strict';

const SUPABASE_URL='https://dlaiacatpcgbzmumtggw.supabase.co';
const SUPABASE_KEY='sb_publishable_1_IEt89WvEBEhykAfS7rvw_jF7WwD6l';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>{if(v===''||v==null)return null;const x=Number(String(v).replace(',','.'));return Number.isFinite(x)?x:null};
const trainingName=v=>String(v||'Тренировка 1').trim()||'Тренировка 1';
const trainingSort=v=>{const m=String(v||'').match(/(\d+)/);return m?Number(m[1]):999};
let user=null, role=null, onlineAccess=false;

function toast(msg,err=false){
  const el=$('toast');if(!el)return;
  el.textContent=msg;el.className='toast'+(err?' err':'');el.classList.remove('hidden');
  clearTimeout(el._v181t);el._v181t=setTimeout(()=>el.classList.add('hidden'),3000);
}
async function identity(){
  const s=await db.auth.getSession();user=s.data.session?.user||null;role=null;onlineAccess=false;
  if(!user)return;
  const r=await db.from('user_roles').select('role').eq('user_id',user.id).maybeSingle();
  role=r.data?.role||'client';
  if(role==='client'){
    const q=await db.from('trainer_clients').select('online_access').eq('client_id',user.id).eq('status','active').limit(1).maybeSingle();
    onlineAccess=Boolean(q.data?.online_access);
  }
}
function setActive(){document.querySelectorAll('#nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page==='online'))}
async function openOnline(){await identity();setActive();if(role==='trainer')return trainerHome();return clientHome()}
function overrideOnlineButton(){
  const nav=$('nav');if(!nav||nav.classList.contains('hidden'))return;
  const old=nav.querySelector('[data-page="online"]');if(!old||old.dataset.v181==='1')return;
  const b=old.cloneNode(true);b.dataset.v181='1';b.innerHTML='<b>🌐</b>Онлайн';b.onclick=openOnline;old.replaceWith(b);
}
const navObs=new MutationObserver(()=>overrideOnlineButton());

async function listExercises(){const q=await db.from('exercises').select('id,name,category,equipment,muscle_group').eq('trainer_id',user.id).eq('archived',false).order('name');if(q.error)throw q.error;return q.data||[]}
async function listTemplates(){const q=await db.from('program_templates').select('id,name,description,online_week_number,created_at,template_exercises(id,day_label)').eq('trainer_id',user.id).eq('online_only',true).order('online_week_number').order('created_at',{ascending:false});if(q.error)throw q.error;return q.data||[]}
async function listOnlineClients(){const l=await db.from('trainer_clients').select('client_id,online_access,status').eq('trainer_id',user.id).eq('status','active');if(l.error)throw l.error;if(!l.data?.length)return[];const ids=l.data.map(x=>x.client_id),p=await db.from('profiles').select('id,full_name').in('id',ids);if(p.error)throw p.error;const m=new Map(l.data.map(x=>[x.client_id,x]));return (p.data||[]).map(x=>({...x,...m.get(x.id)})).sort((a,b)=>(a.full_name||'').localeCompare(b.full_name||'','ru'))}
function countTrainings(t){return new Set((t.template_exercises||[]).map(x=>trainingName(x.day_label))).size||0}
function backButton(label='Назад'){return `<button class="o181-back" type="button">← <span>${esc(label)}</span></button>`}

async function trainerHome(){
  const main=$('main');if(!main)return;main.innerHTML='<div class="spinner"></div>';
  try{
    const [templates,clients]=await Promise.all([listTemplates(),listOnlineClients()]);const onlineClients=clients.filter(x=>x.online_access);
    main.innerHTML=`<div class="online181 trainer-online181"><header class="o181-page-head"><div><div class="o181-kicker">DENISFIT ONLINE</div><h1>Онлайн ведение</h1><p>Шаблоны по неделям, программы клиентов и БЖУ.</p></div><button id="o181NewTemplate" class="o181-accent-btn">＋ Создать шаблон</button></header><section class="o181-section"><div class="o181-section-title"><span>Шаблоны по неделям</span><small>6 недель</small></div><div class="o181-week-stack">${Array.from({length:6},(_,i)=>{const w=i+1,rows=templates.filter(t=>Number(t.online_week_number)===w);return `<div class="o181-week-panel"><div class="o181-week-head"><div><b>Неделя ${w}</b><span>${rows.length?`${rows.length} шабл.`:'Пока пусто'}</span></div><button data-o181-new-week="${w}">＋</button></div><div class="o181-template-list">${rows.length?rows.map(t=>`<article class="o181-template-card"><div><div class="o181-template-title">${esc(t.name)}</div><div class="o181-template-meta">${countTrainings(t)} трен. · ${(t.template_exercises||[]).length} упр.</div></div><div class="o181-card-actions"><button data-o181-edit-template="${t.id}">Редактировать</button><button class="danger" data-o181-delete-template="${t.id}">Удалить</button></div></article>`).join(''):`<div class="o181-empty">Добавь первый шаблон недели.</div>`}</div></div>`}).join('')}</div></section><section class="o181-section"><div class="o181-section-title"><span>Клиенты онлайн</span><small>${onlineClients.length}</small></div><div class="o181-client-list">${onlineClients.length?onlineClients.map(c=>`<button class="o181-client-card" data-o181-client="${c.id}"><span class="o181-avatar">🌐</span><span><b>${esc(c.full_name||'Клиент')}</b><small>Недели и БЖУ</small></span><i>›</i></button>`).join(''):`<div class="o181-empty">Включи «Онлайн ведение» в карточке клиента.</div>`}</div></section></div>`;
    $('o181NewTemplate').onclick=()=>trainerTemplateCreate(1);
    document.querySelectorAll('[data-o181-new-week]').forEach(b=>b.onclick=()=>trainerTemplateCreate(Number(b.dataset.o181NewWeek)));
    document.querySelectorAll('[data-o181-edit-template]').forEach(b=>b.onclick=()=>trainerTemplateEditor(b.dataset.o181EditTemplate));
    document.querySelectorAll('[data-o181-delete-template]').forEach(b=>b.onclick=async()=>{if(!confirm('Удалить шаблон? Уже назначенные клиентам программы останутся.'))return;const id=b.dataset.o181DeleteTemplate;const d=await db.from('template_exercises').delete().eq('template_id',id);if(d.error)return toast(d.error.message,true);const q=await db.from('program_templates').delete().eq('id',id).eq('trainer_id',user.id);if(q.error)return toast(q.error.message,true);toast('Шаблон удалён');trainerHome()});
    document.querySelectorAll('[data-o181-client]').forEach(b=>b.onclick=()=>trainerClient(b.dataset.o181Client));
  }catch(e){main.innerHTML=`<div class="card"><b>Ошибка</b><p class="muted">${esc(e.message||e)}</p></div>`}
}

function trainerTemplateCreate(week){
  const main=$('main');main.innerHTML=`<div class="online181">${backButton('Онлайн ведение')}<div class="o181-editor-shell"><div class="o181-kicker">НОВЫЙ ШАБЛОН</div><h1>Неделя ${week}</h1><div class="o181-form-card"><label>Неделя<select id="o181TplWeek">${Array.from({length:6},(_,i)=>`<option value="${i+1}" ${i+1===week?'selected':''}>Неделя ${i+1}</option>`).join('')}</select></label><label>Название<input id="o181TplName" placeholder="Например: Верх / низ"></label><label>Описание<input id="o181TplDesc" placeholder="Цель или акцент недели"></label><button id="o181CreateTpl" class="o181-accent-btn">Создать и добавить упражнения</button></div></div></div>`;
  main.querySelector('.o181-back').onclick=trainerHome;
  $('o181CreateTpl').onclick=async()=>{const name=$('o181TplName').value.trim(),w=Number($('o181TplWeek').value);if(!name)return toast('Введите название',true);const q=await db.from('program_templates').insert({trainer_id:user.id,name,description:$('o181TplDesc').value.trim(),online_only:true,online_week_number:w}).select('id').single();if(q.error)return toast(q.error.message,true);trainerTemplateEditor(q.data.id)};
}

async function trainerTemplateEditor(templateId){
  const main=$('main');main.innerHTML='<div class="spinner"></div>';
  try{
    const [tQ,iQ,ex]=await Promise.all([db.from('program_templates').select('id,name,description,online_week_number').eq('id',templateId).eq('trainer_id',user.id).single(),db.from('template_exercises').select('id,exercise_id,day_label,sort_order,target_sets,target_reps,target_rpe,notes,exercises(name,category,equipment)').eq('template_id',templateId).order('sort_order'),listExercises()]);if(tQ.error)throw tQ.error;if(iQ.error)throw iQ.error;const t=tQ.data,items=iQ.data||[];const groups=[...new Set(items.map(x=>trainingName(x.day_label)))].sort((a,b)=>trainingSort(a)-trainingSort(b));
    main.innerHTML=`<div class="online181">${backButton('Шаблоны')}<header class="o181-page-head compact"><div><div class="o181-kicker">НЕДЕЛЯ ${t.online_week_number}</div><h1>${esc(t.name)}</h1><p>${esc(t.description||'Онлайн-шаблон')}</p></div></header><div class="o181-form-card"><div class="o181-section-title"><span>Добавить упражнение</span></div><label>Тренировка<select id="o181Training">${Array.from({length:7},(_,i)=>`<option>Тренировка ${i+1}</option>`).join('')}</select></label><label>Упражнение<select id="o181Exercise">${ex.map(x=>`<option value="${x.id}">${esc(x.name)}${x.muscle_group?` · ${esc(x.muscle_group)}`:''}</option>`).join('')}</select></label><div class="o181-two"><label>Подходы<input id="o181Sets" type="number" min="1" value="3"></label><label>Повторы<input id="o181Reps" value="8–10"></label></div><label>Комментарий<input id="o181Notes" placeholder="Техника / темп / акцент"></label><button id="o181AddExercise" class="o181-accent-btn">＋ Добавить упражнение</button></div><div class="o181-training-groups">${groups.length?groups.map(g=>{const rows=items.filter(x=>trainingName(x.day_label)===g);return `<section class="o181-training-group"><div class="o181-training-title"><b>${esc(g)}</b><span>${rows.length} упр.</span></div>${rows.map((it,idx)=>`<div class="o181-editor-ex"><span class="o181-mini-badge">${idx+1}</span><div><b>${esc(it.exercises?.name||'Упражнение')}</b><small>${it.target_sets||1} подх. · ${esc(it.target_reps||'—')}</small></div><button data-o181-remove-ex="${it.id}">×</button></div>`).join('')}</section>`}).join(''):`<div class="o181-empty">Добавь первое упражнение.</div>`}</div><button id="o181FinishTpl" class="o181-secondary-btn">Готово</button></div>`;
    main.querySelector('.o181-back').onclick=trainerHome;
    $('o181AddExercise').onclick=async()=>{const exercise=$('o181Exercise').value,sets=Number($('o181Sets').value);if(!exercise||!Number.isInteger(sets)||sets<1)return toast('Проверь упражнение и подходы',true);const q=await db.from('template_exercises').insert({template_id:templateId,exercise_id:exercise,day_label:$('o181Training').value,sort_order:items.length+1,target_sets:sets,target_reps:$('o181Reps').value.trim()||'8–10',notes:$('o181Notes').value.trim()||null});if(q.error)return toast(q.error.message,true);trainerTemplateEditor(templateId)};
    document.querySelectorAll('[data-o181-remove-ex]').forEach(b=>b.onclick=async()=>{const q=await db.from('template_exercises').delete().eq('id',b.dataset.o181RemoveEx);if(q.error)return toast(q.error.message,true);trainerTemplateEditor(templateId)});$('o181FinishTpl').onclick=trainerHome;
  }catch(e){main.innerHTML=`<div class="card"><b>Ошибка</b><p class="muted">${esc(e.message||e)}</p></div>`}
}

async function trainerClient(clientId){
  const main=$('main');main.innerHTML='<div class="spinner"></div>';
  try{
    const clients=await listOnlineClients(),c=clients.find(x=>x.id===clientId);if(!c)return trainerHome();const [templates,pQ,nQ]=await Promise.all([listTemplates(),db.from('training_programs').select('id,name,online_week_number').eq('trainer_id',user.id).eq('client_id',clientId).eq('online_only',true).eq('active',true).order('created_at',{ascending:false}),db.from('client_nutrition_targets').select('protein_g,fat_g,carbs_g').eq('trainer_id',user.id).eq('client_id',clientId).maybeSingle()]);if(pQ.error)throw pQ.error;if(nQ.error)throw nQ.error;const programs=pQ.data||[],macro=nQ.data||{};
    main.innerHTML=`<div class="online181">${backButton('Онлайн ведение')}<header class="o181-page-head compact"><div><div class="o181-kicker">КЛИЕНТ ОНЛАЙН</div><h1>${esc(c.full_name||'Клиент')}</h1><p>Программа на 6 недель и БЖУ.</p></div></header><section class="o181-macro-card"><div class="o181-section-title"><span>Питание · БЖУ</span></div><div class="o181-macro-edit"><label><span>Белки</span><input id="o181Protein" inputmode="decimal" value="${macro.protein_g??''}"><small>г</small></label><label><span>Жиры</span><input id="o181Fat" inputmode="decimal" value="${macro.fat_g??''}"><small>г</small></label><label><span>Углеводы</span><input id="o181Carbs" inputmode="decimal" value="${macro.carbs_g??''}"><small>г</small></label></div><button id="o181SaveMacro" class="o181-accent-btn">Сохранить БЖУ</button></section><section class="o181-section"><div class="o181-section-title"><span>Тренировочный план</span><small>6 недель</small></div><div class="o181-week-stack">${Array.from({length:6},(_,i)=>{const w=i+1,p=programs.find(x=>Number(x.online_week_number)===w),rows=templates.filter(x=>Number(x.online_week_number)===w);return `<div class="o181-week-panel trainer-assignment ${p?'ready':''}"><div class="o181-week-head"><div><b>Неделя ${w}</b><span>${p?esc(p.name):'Не назначена'}</span></div><span class="o181-status">${p?'ГОТОВО':'ПУСТО'}</span></div><select id="o181Assign${w}"><option value="">Выбери шаблон</option>${rows.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select><button data-o181-assign="${w}" class="${p?'o181-secondary-btn':'o181-accent-btn'}">${p?'Заменить':'Добавить'} шаблон</button></div>`}).join('')}</div></section></div>`;
    main.querySelector('.o181-back').onclick=trainerHome;
    $('o181SaveMacro').onclick=async()=>{const vals={protein_g:num($('o181Protein').value)||0,fat_g:num($('o181Fat').value)||0,carbs_g:num($('o181Carbs').value)||0};if(Object.values(vals).some(v=>v<0))return toast('БЖУ не могут быть отрицательными',true);const q=await db.from('client_nutrition_targets').upsert({trainer_id:user.id,client_id:clientId,...vals,updated_at:new Date().toISOString()},{onConflict:'trainer_id,client_id'});if(q.error)return toast(q.error.message,true);toast('БЖУ сохранены')};
    document.querySelectorAll('[data-o181-assign]').forEach(b=>b.onclick=async()=>{const w=Number(b.dataset.o181Assign),tid=$(`o181Assign${w}`).value;if(!tid)return toast('Выбери шаблон недели',true);const q=await db.rpc('assign_online_template',{p_template_id:tid,p_client_id:clientId});if(q.error)return toast(q.error.message,true);toast(`Неделя ${w} назначена`);trainerClient(clientId)});
  }catch(e){main.innerHTML=`<div class="card"><b>Ошибка</b><p class="muted">${esc(e.message||e)}</p></div>`}
}

async function clientHome(){
  const main=$('main');if(!main)return;main.innerHTML='<div class="spinner"></div>';
  try{
    await identity();if(!onlineAccess){main.innerHTML='<div class="online181"><h1>Онлайн ведение</h1><div class="o181-empty">Онлайн-доступ не включён тренером.</div></div>';return}
    const [pQ,nQ]=await Promise.all([db.from('training_programs').select('id,name,description,online_week_number,created_at').eq('client_id',user.id).eq('online_only',true).eq('active',true).order('created_at',{ascending:false}),db.from('client_nutrition_targets').select('protein_g,fat_g,carbs_g').eq('client_id',user.id).limit(1).maybeSingle()]);if(pQ.error)throw pQ.error;if(nQ.error)throw nQ.error;const programs=pQ.data||[],macro=nQ.data||{};
    main.innerHTML=`<div class="online181 client-online181"><header class="o181-page-head"><div><div class="o181-kicker">DENISFIT ONLINE</div><h1>Моя программа</h1><p>Тренировочный план на 6 недель.</p></div></header><section class="o181-program-card"><div class="o181-program-title"><span>ТРЕНИРОВОЧНЫЙ ПЛАН</span><small>6 недель</small></div><div class="o181-week-list">${Array.from({length:6},(_,i)=>{const w=i+1,p=programs.find(x=>Number(x.online_week_number)===w);return `<button class="o181-client-week ${p?'ready':''}" data-o181-week="${w}"><span><b>Неделя ${w}</b><small>${p?esc(p.name):'Ожидает программу'}</small></span><i>${p?'›':'•'}</i></button>`}).join('')}</div></section><section class="o181-nutrition-card"><div class="o181-program-title"><span>ПИТАНИЕ</span><small>БЖУ</small></div><div class="o181-macro-view"><div><span>Б</span><strong>${Number(macro.protein_g||0)}</strong><small>г</small></div><div><span>Ж</span><strong>${Number(macro.fat_g||0)}</strong><small>г</small></div><div><span>У</span><strong>${Number(macro.carbs_g||0)}</strong><small>г</small></div></div></section></div>`;
    document.querySelectorAll('[data-o181-week]').forEach(b=>b.onclick=()=>clientWeek(Number(b.dataset.o181Week)));
  }catch(e){main.innerHTML=`<div class="card"><b>Ошибка</b><p class="muted">${esc(e.message||e)}</p></div>`}
}

async function clientWeek(week){
  const main=$('main');main.innerHTML='<div class="spinner"></div>';
  try{
    const pQ=await db.from('training_programs').select('id,name,description,online_week_number').eq('client_id',user.id).eq('online_only',true).eq('active',true).eq('online_week_number',week).order('created_at',{ascending:false}).limit(1).maybeSingle();if(pQ.error)throw pQ.error;const program=pQ.data;if(!program){main.innerHTML=`<div class="online181">${backButton('Моя программа')}<h1>Неделя ${week}</h1><div class="o181-empty">Тренер пока не добавил программу.</div></div>`;main.querySelector('.o181-back').onclick=clientHome;return}
    const eQ=await db.from('program_exercises').select('id,exercise_id,day_label,sort_order,target_sets,target_reps,target_rpe,notes,exercises(name,category,equipment)').eq('program_id',program.id).order('sort_order');if(eQ.error)throw eQ.error;const items=eQ.data||[],groups=[...new Set(items.map(x=>trainingName(x.day_label)))].sort((a,b)=>trainingSort(a)-trainingSort(b));
    main.innerHTML=`<div class="online181 client-online181">${backButton('Моя программа')}<header class="o181-page-head compact"><div><div class="o181-kicker">НЕДЕЛЯ ${week}</div><h1>${esc(program.name)}</h1><p>${esc(program.description||'Программа от тренера')}</p></div></header><section class="o181-program-card"><div class="o181-program-title"><span>Неделя ${week}</span><small>${groups.length} трен.</small></div><div class="o181-training-list">${groups.length?groups.map(g=>{const rows=items.filter(x=>trainingName(x.day_label)===g);return `<button class="o181-training-card" data-o181-training="${esc(g)}"><span><b>${esc(g)}</b><small>${rows.length} упражнений</small></span><i>›</i></button>`}).join(''):`<div class="o181-empty">В этой неделе пока нет тренировок.</div>`}</div></section></div>`;
    main.querySelector('.o181-back').onclick=clientHome;document.querySelectorAll('[data-o181-training]').forEach(b=>b.onclick=()=>clientTraining(week,program,b.dataset.o181Training,items));
  }catch(e){main.innerHTML=`<div class="card"><b>Ошибка</b><p class="muted">${esc(e.message||e)}</p></div>`}
}
function badgeFor(i){return `${Math.floor(i/2)+1}${i%2?'b':'a'}`}

async function clientTraining(week,program,dayLabel,allItems){
  const main=$('main');main.innerHTML='<div class="spinner"></div>';
  try{
    const items=(allItems||[]).filter(x=>trainingName(x.day_label)===trainingName(dayLabel)),note=`Онлайн · Неделя ${week} · ${trainingName(dayLabel)}`;
    const sQ=await db.from('workout_sessions').select('id').eq('client_id',user.id).eq('program_id',program.id).eq('notes',note).order('created_at',{ascending:false}).limit(1).maybeSingle();if(sQ.error)throw sQ.error;let workout=sQ.data||null,oldSets=[];if(workout){const q=await db.from('workout_sets').select('exercise_id,set_number,weight').eq('session_id',workout.id).order('set_number');if(q.error)throw q.error;oldSets=q.data||[]}
    main.innerHTML=`<div class="online181 client-online181 training-detail181">${backButton(`Неделя ${week}`)}<header class="o181-page-head compact"><div><div class="o181-kicker">НЕДЕЛЯ ${week}</div><h1>${esc(trainingName(dayLabel))}</h1><p>${esc(program.name)}</p></div></header><div class="o181-plan-chip">${esc(program.description||'Программа от тренера')}</div><section class="o181-exercise-flow">${items.length?items.map((it,idx)=>{const existing=oldSets.filter(x=>x.exercise_id===it.exercise_id),count=Math.max(existing.length,Number(it.target_sets||3),1),boxes=Array.from({length:count},(_,j)=>{const old=existing.find(x=>Number(x.set_number)===j+1);return `<div class="o181-set-box"><span>${esc(it.target_reps||'—')}</span><input class="o181-set-weight" inputmode="decimal" value="${old?.weight??''}" placeholder="кг"><small>${j+1} подход</small></div>`}).join('');return `<article class="o181-exercise" data-o181-exercise="${it.exercise_id}" data-target-reps="${esc(it.target_reps||'')}"><div class="o181-exercise-rail"><span>${badgeFor(idx)}</span>${idx<items.length-1?'<i></i>':''}</div><div class="o181-exercise-body"><div class="o181-exercise-name"><b>${esc(it.exercises?.name||'Упражнение')}</b><span>›</span></div>${it.notes?`<p>${esc(it.notes)}</p>`:''}<div class="o181-sets-label">Повт</div><div class="o181-set-strip">${boxes}</div><div class="o181-set-actions"><button data-o181-remove-set>- подход</button><button data-o181-add-set>＋ подход</button></div></div></article>`}).join(''):`<div class="o181-empty">В тренировке пока нет упражнений.</div>`}</section>${items.length?'<button id="o181SaveTraining" class="o181-accent-btn sticky-save181">Сохранить тренировку</button>':''}</div>`;
    main.querySelector('.o181-back').onclick=()=>clientWeek(week);
    document.querySelectorAll('[data-o181-add-set]').forEach(b=>b.onclick=()=>{const ex=b.closest('[data-o181-exercise]'),strip=ex.querySelector('.o181-set-strip'),n=strip.children.length+1,reps=ex.dataset.targetReps||'—';const box=document.createElement('div');box.className='o181-set-box';box.innerHTML=`<span>${esc(reps)}</span><input class="o181-set-weight" inputmode="decimal" placeholder="кг"><small>${n} подход</small>`;strip.appendChild(box)});
    document.querySelectorAll('[data-o181-remove-set]').forEach(b=>b.onclick=()=>{const strip=b.closest('[data-o181-exercise]').querySelector('.o181-set-strip');if(strip.children.length>1)strip.lastElementChild.remove()});
    if($('o181SaveTraining'))$('o181SaveTraining').onclick=async()=>{const exercises=Array.from(document.querySelectorAll('[data-o181-exercise]')),rows=[];for(const ex of exercises){const eid=ex.dataset.o181Exercise,inputs=Array.from(ex.querySelectorAll('.o181-set-weight'));for(let i=0;i<inputs.length;i++){const w=num(inputs[i].value);if(w!=null&&w<0)return toast('Вес не может быть отрицательным',true);rows.push({exercise_id:eid,set_number:i+1,weight:w,reps:null,rpe:null})}}const btn=$('o181SaveTraining');btn.disabled=true;btn.textContent='Сохраняю...';try{if(!workout){const q=await db.from('workout_sessions').insert({client_id:user.id,program_id:program.id,performed_at:new Date().toISOString(),notes:note}).select('id').single();if(q.error)throw q.error;workout=q.data}else{const d=await db.from('workout_sets').delete().eq('session_id',workout.id);if(d.error)throw d.error}if(rows.length){const q=await db.from('workout_sets').insert(rows.map(r=>({session_id:workout.id,...r})));if(q.error)throw q.error}const c=await db.rpc('confirm_my_training',{p_session_id:workout.id});if(c.error)throw c.error;showCelebrate();toast('Тренировка сохранена')}catch(e){toast(e.message||'Не удалось сохранить тренировку',true)}finally{btn.disabled=false;btn.textContent='Сохранить тренировку'}};
  }catch(e){main.innerHTML=`<div class="card"><b>Ошибка</b><p class="muted">${esc(e.message||e)}</p></div>`}
}
function showCelebrate(){if(document.querySelector('.o181-celebrate'))return;const el=document.createElement('div');el.className='o181-celebrate';el.innerHTML='<div class="o181-celebrate-card"><div>🔥</div><small>ТРЕНИРОВКА ЗАВЕРШЕНА</small><h2>Ты ещё ближе<br>к своей цели</h2><p>Ещё одна тренировка в копилке.</p><button>Продолжить</button></div>';document.body.appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));const close=()=>{el.classList.remove('show');setTimeout(()=>el.remove(),220)};el.querySelector('button').onclick=close;el.onclick=e=>{if(e.target===el)close()};setTimeout(close,4200)}

async function boot(){await identity();overrideOnlineButton();const nav=$('nav');if(nav)navObs.observe(nav,{childList:true,subtree:true})}
window.addEventListener('load',()=>setTimeout(boot,300));db.auth.onAuthStateChange(()=>setTimeout(async()=>{await identity();overrideOnlineButton()},250));
})();