const fs=require('fs');
const {chromium}=require('playwright-core');
(async()=>{
  const chrome=process.env.CHROME_PATH;if(!chrome)throw new Error('CHROME_PATH is required');
  const browser=await chromium.launch({headless:true,executablePath:chrome,args:['--no-sandbox']});
  const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
  await page.setContent('<!doctype html><html><body><main id="main"></main><nav id="nav"><button data-page="schedule">Расписание</button></nav></body></html>');
  await page.evaluate(()=>{
    window.confirm=()=>true;
    const store=new Map([['df_v188_client','client-1']]);Object.defineProperty(window,'sessionStorage',{configurable:true,value:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)}});
    window.__programs=[{id:'p1',trainer_id:'trainer-1',client_id:'client-1',name:'Ноги',description:'A',active:true},{id:'p2',trainer_id:'trainer-1',client_id:'client-1',name:'Спина',description:'B',active:true}];
    window.__templates=[{id:'t1',trainer_id:'trainer-1',name:'Шаблон 1',description:'A',template_exercises:[{id:'te1'}]},{id:'t2',trainer_id:'trainer-1',name:'Шаблон 2',description:'B',template_exercises:[{id:'te2'},{id:'te3'}]}];
    window.__packages=[{id:'b1',trainer_id:'trainer-1',client_id:'client-1',entry_mode:'purchase',package_name:'Блок 5',total_sessions:5,used_sessions:5,amount_paid:15000,paid_at:'2026-07-01T10:00:00Z',status:'exhausted',created_at:'2026-07-01T10:00:00Z'},{id:'b2',trainer_id:'trainer-1',client_id:'client-1',entry_mode:'purchase',package_name:'Блок 10',total_sessions:10,used_sessions:2,amount_paid:35000,paid_at:'2026-08-01T10:00:00Z',status:'active',created_at:'2026-08-01T10:00:00Z'},{id:'r1',trainer_id:'trainer-1',client_id:'client-1',entry_mode:'remaining',package_name:'Остаток 5',total_sessions:5,used_sessions:0,amount_paid:0,status:'active',created_at:'2026-06-01T10:00:00Z'},{id:'s1',trainer_id:'trainer-1',client_id:'client-1',entry_mode:'purchase',package_name:'Разовая',total_sessions:1,used_sessions:1,amount_paid:3000,status:'exhausted',created_at:'2026-08-10T10:00:00Z'}];
    window.__assignments=[{id:'a1',trainer_id:'trainer-1',client_id:'client-1',program_id:'p1',program_name:'Ноги',day_label:'Тренировка',status:'scheduled',schedule_event_id:'ev1'},{id:'a2',trainer_id:'trainer-1',client_id:'client-1',program_id:'p1',program_name:'Ноги',day_label:'Тренировка',status:'completed',schedule_event_id:'old'}];
    window.__events=[{id:'ev1',trainer_id:'trainer-1',starts_at:'2026-08-21T09:00:00Z',ends_at:'2026-08-21T10:00:00Z',training_type:'personal',status:'completed',notes:''}];
    window.__parts=[{id:'part1',event_id:'ev1',client_id:'client-1',package_id:'b2',payment_mode:'package'}];
    class Q{constructor(t){this.t=t;this.f={};this.op='select';this.patch=null;this.rows=null}select(){return this}eq(k,v){this.f[k]=v;return this}neq(){return this}lt(){return this}gt(){return this}order(){return this}limit(){return this}in(){return this}update(x){this.op='update';this.patch=x;return this}insert(x){this.op='insert';this.rows=Array.isArray(x)?x:[x];return this}delete(){this.op='delete';return this}maybeSingle(){return this._exec(true)}single(){return this._exec(true)}then(a,b){return this._exec(false).then(a,b)}async _exec(single){let data=[];const match=x=>Object.entries(this.f).every(([k,v])=>x[k]===v);if(this.t==='user_roles')data=[{role:'trainer'}];if(this.t==='training_programs'){if(this.op==='update')window.__programs.filter(match).forEach(x=>Object.assign(x,this.patch));data=window.__programs.filter(match)}if(this.t==='client_packages')data=window.__packages.filter(match);if(this.t==='program_templates'){if(this.op==='delete')window.__templates=window.__templates.filter(x=>!match(x));data=window.__templates.filter(match)}if(this.t==='assigned_workouts'){if(this.op==='update')window.__assignments.filter(match).forEach(x=>Object.assign(x,this.patch));if(this.op==='insert'){window.__assignments.push(...this.rows);data=this.rows}else data=window.__assignments.filter(match)}if(this.t==='schedule_events'){if(this.op==='insert'){const row={id:'ev'+(window.__events.length+1),...this.rows[0]};window.__events.push(row);data=[row]}else if(this.op==='delete'){window.__events=window.__events.filter(x=>!match(x));data=[]}else data=window.__events.filter(match)}if(this.t==='schedule_event_clients'){if(this.op==='insert'){window.__parts.push(...this.rows);data=this.rows}else data=window.__parts.filter(match)}if(this.t==='profiles')data=[{id:'client-1',full_name:'Дарья'}];return {data:single?(data[0]||null):data,error:null}}
    }
    const db={auth:{getSession:async()=>({data:{session:{user:{id:'trainer-1',is_anonymous:false}}}})},from:t=>new Q(t)};window.supabase={createClient:()=>db};
  });
  await page.evaluate(()=>{document.querySelector('#main').innerHTML='<button id="assignFromClient">Назначить</button><button id="saveClientPlan">Сохранить</button><div class="section-title">Абонементы</div><div class="card">Абонементы</div><div class="section-title">Программы</div><div class="card legacy">legacy</div><button id="deleteClient">Удалить клиента</button>'});
  await page.addScriptTag({content:fs.readFileSync('client-workflow-v191.js','utf8')});
  await page.waitForSelector('#dfv191ClientPrograms [data-client-program]');await page.waitForSelector('#dfv191PackageStats');
  if(await page.locator('[data-client-program]').count()!==2)throw new Error('Client program list missing');
  const stats=(await page.locator('#dfv191PackageStats').innerText()).replace(/\s+/g,' ');if(!stats.includes('Куплено блоков')||!stats.includes('15')||!stats.includes('50 000'))throw new Error('Block purchase statistics incorrect: '+stats);
  await page.locator('[data-remove-client-program]').first().click();await page.waitForTimeout(120);const state=await page.evaluate(()=>({p:window.__programs.find(x=>x.id==='p1'),a:window.__assignments.find(x=>x.id==='a1'),h:window.__assignments.find(x=>x.id==='a2')}));if(state.p.active!==false||state.a.status!=='cancelled'||state.h.status!=='completed')throw new Error('Client template removal unsafe');
  await page.evaluate(()=>{document.querySelector('#main').innerHTML='<h1>Программы</h1><div class="client-actions-grid"><button id="programCreateTemplate">Создать</button><button id="programShowTemplates">Шаблоны</button></div>'});await page.waitForTimeout(150);await page.waitForSelector('#dfv191TemplateManager [data-template-row]');if(await page.locator('[data-template-row]').count()!==2)throw new Error('Template manager missing');await page.locator('[data-delete-template-v191]').first().click();await page.waitForTimeout(100);if(await page.locator('[data-template-row]').count()!==1)throw new Error('Global template delete failed');
  await page.evaluate(()=>{window.__assignments.push({id:'a3',trainer_id:'trainer-1',client_id:'client-1',program_id:'p2',program_name:'Спина',day_label:'Тренировка',status:'completed',schedule_event_id:'ev1'});document.querySelector('#main').innerHTML='<button id="done" data-event-status="ev1|completed">Выполнить</button>'});await page.locator('#done').click();await page.waitForSelector('#dfv191Modal.open');const modal=await page.locator('#dfv191Modal').innerText();if(!modal.includes('Записать сразу?'))throw new Error('Next booking popup missing');await page.locator('#dfv191Book').click();await page.waitForTimeout(150);const next=await page.evaluate(()=>({events:window.__events.length,parts:window.__parts.length,assign:window.__assignments.filter(x=>x.schedule_event_id==='ev2').length}));if(next.events!==2||next.parts!==2||next.assign<1)throw new Error('Next booking was not created');
  if(errors.length)throw new Error(errors.join(' | '));await browser.close();console.log('DenisFit client workflow v191: PASS');
})().catch(e=>{console.error(e);process.exit(1)});