const fs=require('fs');
const {chromium}=require('playwright-core');
(async()=>{
 const chrome=process.env.CHROME_PATH;if(!chrome)throw new Error('CHROME_PATH');
 const browser=await chromium.launch({headless:true,executablePath:chrome,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.setContent('<!doctype html><html><body><main id="main"></main><nav id="nav"><button data-page="schedule">Расписание</button></nav><div id="roleBadge">ТРЕНЕР</div></body></html>');
 await page.evaluate(()=>{
  window.confirm=()=>true;const st=new Map([['df_v188_client','c1']]);Object.defineProperty(window,'sessionStorage',{value:{getItem:k=>st.get(k)||null,setItem:(k,v)=>st.set(k,String(v))}});
  window.P=[{id:'p1',trainer_id:'t1',client_id:'c1',name:'Ноги',active:true,description:'A',created_at:'2026-08-01'},{id:'p2',trainer_id:'t1',client_id:'c1',name:'Спина',active:true,description:'B',created_at:'2026-08-02'}];
  window.T=[{id:'tA',trainer_id:'t1',name:'Шаблон A',description:'A',created_at:'2026-08-01',template_exercises:[{id:'1'}]},{id:'tB',trainer_id:'t1',name:'Шаблон B',description:'B',created_at:'2026-08-02',template_exercises:[{id:'2'}]}];
  window.K=[{id:'k1',trainer_id:'t1',client_id:'c1',package_name:'Блок 5',total_sessions:5,used_sessions:5,entry_mode:'purchase',amount_paid:15000,paid_at:'2026-07-01T10:00:00Z',status:'exhausted',created_at:'2026-07-01'},{id:'k2',trainer_id:'t1',client_id:'c1',package_name:'Блок 10',total_sessions:10,used_sessions:2,entry_mode:'purchase',amount_paid:35000,paid_at:'2026-08-01T10:00:00Z',status:'active',created_at:'2026-08-01'}];
  window.A=[{id:'a1',trainer_id:'t1',client_id:'c1',program_id:'p1',program_name:'Ноги',day_label:'Тренировка',status:'scheduled',schedule_event_id:'e1'}];
  window.E=[{id:'e1',trainer_id:'t1',starts_at:'2026-08-21T09:00:00Z',ends_at:'2026-08-21T10:00:00Z',training_type:'personal',status:'completed',notes:''}];window.C=[{event_id:'e1',client_id:'c1',package_id:'k2',payment_mode:'package'}];
  class Q{constructor(t){this.t=t;this.f={};this.op='select';this.patch=null;this.rows=null}select(){return this}eq(k,v){this.f[k]=v;return this}neq(){return this}lt(){return this}gt(){return this}limit(){return this}order(){return this}in(){return this}update(x){this.op='update';this.patch=x;return this}insert(x){this.op='insert';this.rows=Array.isArray(x)?x:[x];return this}delete(){this.op='delete';return this}maybeSingle(){return this.x(true)}single(){return this.x(true)}then(a,b){return this.x(false).then(a,b)}async x(single){const m=o=>Object.entries(this.f).every(([k,v])=>o[k]===v);let d=[];if(this.t==='user_roles')d=[{role:'trainer'}];if(this.t==='training_programs'){if(this.op==='update')window.P.filter(m).forEach(o=>Object.assign(o,this.patch));d=window.P.filter(m)}if(this.t==='client_packages')d=window.K.filter(m);if(this.t==='program_templates'){if(this.op==='delete')window.T=window.T.filter(o=>!m(o));d=window.T.filter(m)}if(this.t==='assigned_workouts'){if(this.op==='update')window.A.filter(m).forEach(o=>Object.assign(o,this.patch));if(this.op==='insert'){window.A.push(...this.rows);d=this.rows}else d=window.A.filter(m)}if(this.t==='schedule_events'){if(this.op==='insert'){const o={id:'e2',...this.rows[0]};window.E.push(o);d=[o]}else if(this.op==='delete'){window.E=window.E.filter(o=>!m(o));d=[]}else d=window.E.filter(m)}if(this.t==='schedule_event_clients'){if(this.op==='insert'){window.C.push(...this.rows);d=this.rows}else d=window.C.filter(m)}if(this.t==='profiles')d=[{id:'c1',full_name:'Дарья'}];return {data:single?(d[0]||null):d,error:null}}
  }
  const db={auth:{getSession:async()=>({data:{session:{user:{id:'t1',is_anonymous:false}}}})},from:t=>new Q(t)};window.supabase={createClient:()=>db};
  document.querySelector('#main').innerHTML='<button id="assignFromClient">Назначить</button><button id="saveClientPlan">Сохранить</button><div class="section-title">Абонементы</div><div class="card">A</div><div class="section-title">Программы</div><div class="card">legacy</div>';
 });
 await page.addScriptTag({content:fs.readFileSync('client-workflow-v192.js','utf8')});
 await page.waitForSelector('#dfv192ClientPrograms [data-v192-remove-client]');await page.waitForSelector('#dfv192PackageStats');
 if(!(await page.locator('#dfv192PackageStats').innerText()).includes('15'))throw new Error('block stats missing');
 await page.locator('[data-v192-remove-client]').first().click();await page.waitForTimeout(100);const rem=await page.evaluate(()=>({p:P[0].active,a:A[0].status}));if(rem.p!==false||rem.a!=='cancelled')throw new Error('client delete failed');
 await page.evaluate(()=>{document.querySelector('#main').innerHTML='<h1>Программы</h1><div class="client-actions-grid"><button id="programCreateTemplate">Создать</button><button id="programShowTemplates">Шаблоны</button></div>'});await page.waitForSelector('#dfv192TemplateManager [data-v192-delete]');await page.locator('[data-v192-delete]').first().click();await page.waitForTimeout(100);if(await page.locator('[data-v192-template]').count()!==1)throw new Error('template delete failed');
 await page.evaluate(()=>{A.push({id:'a2',trainer_id:'t1',client_id:'c1',program_id:'p2',program_name:'Спина',day_label:'Тренировка',status:'completed',schedule_event_id:'e1'});document.querySelector('#main').innerHTML='<button id="done" data-event-status="e1|completed">Выполнить</button>'});await page.locator('#done').click();await page.waitForSelector('#dfv192Modal.open');await page.locator('#dfv192Book').click();await page.waitForTimeout(150);const nxt=await page.evaluate(()=>({e:E.length,c:C.length,a:A.filter(x=>x.schedule_event_id==='e2').length}));if(nxt.e!==2||nxt.c!==2||nxt.a<1)throw new Error('next booking failed');
 if(!(await page.locator('#roleBadge').innerText()).includes('19.8.1'))throw new Error('build marker missing');if(errors.length)throw new Error(errors.join(' | '));await browser.close();console.log('DenisFit direct v192 test: PASS');
})().catch(e=>{console.error(e);process.exit(1)});
